import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to beanify - your world of coffee!</title>
        <meta
          name="beanify - your coffee bean explorer in Vienna"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <header className={styles.header}>
        <Link href="/">
          <a>Home</a>
        </Link>
        <Link href="/admin">
          <a>Admin area</a>
        </Link>
      </header>

      <main className={styles.main}>
        <Image
          src="/cover.png"
          alt=""
          width={640}
          height={320}
          className={styles.logo}
        />
        <h1 className={styles.title}>
          Welcome to beanify - your world of coffee!
        </h1>
      </main>

      <footer className={styles.footer}>
        <p>
          © Jakob Steininger 2021 | enabled by{' '}
          <Link href="https://upleveled.io/">
            <a>UpLeveled</a>
          </Link>
          .
        </p>
      </footer>
    </div>
  );
}
