name: Jest tests
on: push

jobs:
  build:
    name: yarn jest
    # Tell the action to use the latest
    # version of Ubuntu (a Linux flavor)
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      # Set up PostgreSQL with this GitHub Action:
      # https://github.com/Harmon758/postgresql-action
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          # Use GitHub Encrypted Secrets for the credentials
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
          postgresql db: ${{ secrets.PGDATABASE }}
          postgresql user: ${{ secrets.PGUSERNAME }}
          postgresql password: ${{ secrets.PGPASSWORD }}
      - name: Checkout
      # Use the official Checkout action:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # Use the official setup-node action:
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      # Install all dependencies
      - run: yarn server-lockfile
      # Run the Jest unit tests
      - run: yarn server
        env:
          PGHOST: localhost
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSERNAME: ${{ secrets.PGUSERNAME }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          CLOUDINARY_UPLOAD_PRESET: ${{ secrets.CLOUDINARY_UPLOAD_PRESET }}
